name: Build and Release Bazel Target

on:
  push:
    tags:
      - '*'

permissions:
  contents: write  # Ensure the token has write permission for contents

jobs:
  build-osx:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Bazel output
      uses: actions/cache@v2
      id: cache-bazel
      with:
        path: |
          ~/.cache/bazel
          bazel-out
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Build Bazel target
      run: |
        bazelisk build -c opt //xls/public:libxls.dylib //xls/public:c_api

    - name: Create artifact directory
      run: mkdir -p osx-artifacts

    - name: Copy Bazel target to osx-artifacts
      run:
        cp -r bazel-bin/xls/public/libxls.dylib osx-artifacts/
        cp -r bazel-bin/xls/public/libc_api.a osx-artifacts/libxls-osx.a

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx-artifacts
        path: osx-artifacts/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Bazel output
      uses: actions/cache@v2
      id: cache-bazel
      with:
        path: |
          ~/.cache/bazel
          bazel-out
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD') }}
        restore-keys: |
          ${{ runner.os }}-bazel-


    - name: Install Clang-17
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt-get install -y clang-17

    - name: Note Clang version
      run: clang-17 --version

    - name: Build Bazel target
      run: |
        CC=clang-17 CXX=clang++-17 bazelisk build -c opt //xls/public:libxls.so //xls/public:c_api

    - name: Create artifact directory
      run: mkdir -p linux-artifacts

    - name: Copy Bazel target to linux-artifacts
      run:
        cp -r bazel-bin/xls/public/libxls.so linux-artifacts/
        cp -r bazel-bin/xls/public/libc_api.a linux-artifacts/libxls-linux.a

    - name: Tarball stdlib files to linux-artifacts
      run: tar -czvvf linux-artifacts/dslx_stdlib.tar.gz xls/dslx/stdlib/*.x

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-artifacts
        path: linux-artifacts/

  release:
    needs:
      - build-osx
      - build-linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download osx-artifacts
      uses: actions/download-artifact@v2
      with:
        name: osx-artifacts
        path: osx-artifacts

    - name: Download linux-artifacts
      uses: actions/download-artifact@v2
      with:
        name: linux-artifacts
        path: linux-artifacts

    - name: Extract tag name
      id: extract_tag
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "Extracted tag name: $TAG_NAME"

    - name: Download GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.30.0/gh_2.30.0_linux_amd64.tar.gz -o ghcli.tar.gz
        tar -xzf ghcli.tar.gz
        sudo mv gh_2.30.0_linux_amd64/bin/gh /usr/local/bin/

    - name: Create GitHub release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ env.TAG_NAME }}
      run: |
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        gh release create "$TAG_NAME" osx-artifacts/libxls.dylib osx-artifacts/libxls-osx.a linux-artifacts/dslx_stdlib.tar.gz linux-artifacts/libxls.so linux-artifacts/libxls-linux.a --title "Release $TAG_NAME" --notes "Automated release of $TAG_NAME"
