# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Nightly Ubuntu 22.04
on:
on:
  # Trigger on `release` branch while we are developing the action.
  push:
    branches:
      - release
  schedule:
    # Nightly at midnight -- uses UTC, so 7am.
    - cron:  '0 7 * * *'
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    name: Nightly Ubuntu 22.04
    runs-on:
      labels: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # so that git-describe can find previous tags.
      - uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          # Create/use a cache called bazel-cache-22_04-<commit hash>
          # and read the latest cache with prefix bazel-cache-22_04-
          # if it doesn't already exist.
          key: bazel-cache-22_04-${{ github.sha }}
          restore-keys: bazel-cache-22_04-
      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Dist
        run: |
          VERSION=$(git describe --match=v*)
          TAG_EXISTS="$(git tag -l $VERSION)"
          "${GITHUB_WORKSPACE}/bin/bazel" build -c opt --//dist:version=$VERSION --//dist:os=${RUNNER_OS@L} --//dist:arch=${RUNNER_ARCH@L} -- //dist:xls_dist_tar
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG_EXISTS=$TAG_EXISTS" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.TAG_EXISTS == ''
        with:
          tag_name: ${{ env.VERSION }}
          files: bazel-bin/dist/xls-*.*

      - name: Cleanup
        run: |
          rm -fR bazel-bin/dist/ # do not cache released artifacts
