# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Nightly Ubuntu 22.04
on:
  schedule:
    # Nightly at midnight -- uses UTC, so 7am.
    - cron:  '0 7 * * *'
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    name: Nightly Ubuntu 22.04
    runs-on:
      labels: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          # Create/use a cache called bazel-cache-22_04-<commit hash>
          # and read the latest cache with prefix bazel-cache-22_04-
          # if it doesn't already exist.
          key: bazel-cache-22_04-${{ github.sha }}
          restore-keys: bazel-cache-22_04-
      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Bazel fetch
        # Let's fetch all WORKSPACE artifacts to see if they can resolve fully
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" fetch //...

      - name: Bazel Test All (opt)
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test -c opt -- //xls/...
      - name: Dist
        run: |
	  VERSION="$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)"
          "${GITHUB_WORKSPACE}/bin/bazel" build -c opt --//dist:version=${VERSION} --//dist:os=ubuntu_22.04  --//dist:arch=x86_64 -- //dist:xls_dist_tar
	  echo "VERSION=${VERSION}" >> $GITHUB_ENV
	
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bazel-bin/dist/xls-${ env.VERSION }-ubuntu-22.04-x86_64.tar.gz
	  tag_name: ${ env.VERSION }
